---
  - name: "Installing at command"
    yum: name=at state=installed
  
  - name: "Enabling at service"
    service: 
      name: atd 
      enabled: yes
      state: started 

  - name: "scheduling ssh restart in 1 minute"
    at:
      command: systemctl restart sshd >/dev/null
      count: 1
      units: minutes
      unique: yes

  - name: "update pam module"
    lineinfile:
      dest: /etc/pam.d/sshd
      insertbefore: '^auth       include      postlogin'
      line: 'auth    required    pam_oath.so usersfile=/etc/liboath/users.oath window=10 digits=6'
  - debug:
      msg:
        - "Module Enabled!!!!!!! You can login after 1 minute by using Authenticator"
