---
  - lineinfile:
      path: /etc/pam.d/sshd
      regexp: '^auth       substack     password-auth'
      line: '#auth       substack     password-auth'
      backrefs: yes

  - name: "Updating ssh configuraiton"
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^ChallengeResponseAuthentication no'
      line: 'ChallengeResponseAuthentication yes'
      backrefs: yes

  - lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication yes'
      line: 'PasswordAuthentication no'
      backrefs: yes

    service:
      name: sshd
      state: restarted
      enabled: yes

  - debug:
      msg:
        - "Password Prompt Disabled!!!! Login only with Authenticator... "
